# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
